version: '1'

services:
  api:
    image: ander1221/tools_python:0.0.1
    volumes:
      - ./ code/
    ports:
      - 8080:80
    
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    